name: Node.js CI/CD dev

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Change to Project Directory
      run: cd jobsforce-backend

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: |
        cd jobsforce-backend
        npm install

    - name: Build Application (if applicable)
      run: |
        cd jobsforce-backend
        npm run build --if-present

    - name: Restart Application
      run: |
        pm2 restart jobsforce || pm2 start npm --name "jobsforce" -- run start
